# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 864de70c5e94a7bc1273b1a489e8f1b63b4bc76099f5459fd8c9ee5a00fd3a9a4bf3f7bf8955388508b5bace047a6853410d65f04a717c43806e5b916ef528b1

test:
  secret_key_base: 2da863e2cb8beb3838c575a5ef66f2dea8818043cfe3f425382feee70f8b3dbc14ef79d33c685fbd42b1f0249a792162f91284747210fb52d4d1c0f7bc8e6e1f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
